spring.datasource.url=jdbc:postgresql://localhost:5432/personal-expenses-tracker
spring.datasource.username=postgres
spring.datasource.password=senhapost

spring.jpa.hibernate.ddl-auto=update

app.auth.jwt-secret=${APP_AUTH_JWT_SECRET}
app.auth.jwt-expiration-seconds=${APP_AUTH_JWT_EXPIRATION_SECONDS:3600}

server.error.include-stacktrace=never
